insert into locations (
  city,
  location_name,
  score,
  best_time,
  nearby_events,
  competition_level,
  weather_risk
) values
  ('Lowell, MA', 'Lowell Farmers Market', 86, '2 PM - 6 PM', 'Seasonal Thursday market', 'Medium', 'Moderate'),
  ('Lowell, MA', 'Navigation Brewing Company', 84, '5 PM - 9 PM', 'Taproom food truck rotation', 'Medium', 'Low'),
  ('Lowell, MA', 'Western Ave Open Studios', 83, '12 PM - 4 PM', 'Open studios visitor traffic', 'Medium', 'Low'),
  ('Lowell, MA', 'Dutton Street Market', 79, '4 PM - 8 PM', 'Friday and Saturday pop-up village', 'Medium', 'Low'),
  ('Topsfield, MA', 'Topsfield Fair', 96, '11 AM - 9 PM', '2026 fair concessions', 'High', 'Moderate'),
  ('Marshfield, MA', 'Marshfield Fair', 92, '12 PM - 10 PM', 'August 21-30, 2026 fair', 'High', 'Moderate'),
  ('Lancaster, MA', 'Bolton Fair', 88, '11 AM - 8 PM', 'August 14-16, 2026 fair', 'High', 'Moderate'),
  ('Spencer, MA', 'Spencer Fair', 89, '10 AM - 9 PM', 'September 4-7, 2026 fair', 'High', 'Moderate'),
  ('Belchertown, MA', 'Belchertown Fair', 86, '12 PM - 8 PM', '167th Belchertown Fair vendor space', 'Medium', 'Moderate'),
  ('Chester, MA', 'Littleville Fair', 80, '11 AM - 7 PM', 'August 7-9, 2026 fair', 'Medium', 'Moderate'),
  ('Cummington, MA', 'Massachusetts Sheep & Woolcraft Fair', 78, '10 AM - 4 PM', 'Food vendor online application', 'Medium', 'Moderate'),
  ('Peabody, MA', 'Peabody International Festival', 82, '11 AM - 5 PM', '2026 food vendor application', 'Medium', 'Moderate'),
  ('Cambridge, MA', 'Harvard Square MayFair', 90, '12 PM - 6 PM', '2026 food truck application', 'High', 'Moderate'),
  ('West Springfield, MA', 'The Big E', 98, '11 AM - 10 PM', '17-day New England fair', 'High', 'Moderate'),
  ('Princeton, MA', 'Wachusett Mountain Festivals', 87, '11 AM - 5 PM', '2026 festival vendor registration', 'Medium', 'Moderate'),
  ('Durham, CT', 'Durham Fair', 94, '11 AM - 9 PM', 'Connecticut''s largest agricultural fair', 'High', 'Moderate'),
  ('Norwalk, CT', 'Norwalk Oyster Festival', 90, '12 PM - 8 PM', '2026 food vendor inquiry', 'High', 'Moderate'),
  ('Bethlehem, CT', 'Connecticut Garlic & Harvest Festival', 85, '10 AM - 5 PM', 'October 10-11, 2026 festival', 'Medium', 'Moderate'),
  ('Lebanon, CT', 'Connecticut Renaissance Faire', 84, '11 AM - 6 PM', '2026 food vendor application', 'Medium', 'Moderate'),
  ('Unity, ME', 'Common Ground Country Fair', 91, '10 AM - 5 PM', 'MOFGA fair vendor resources', 'High', 'Moderate'),
  ('Pittston, ME', 'Pittston Fair', 77, '11 AM - 8 PM', '2026 agricultural fair', 'Medium', 'Moderate'),
  ('Fort Fairfield, ME', 'Maine Potato Blossom Festival', 82, '11 AM - 7 PM', '2026 vendor application', 'Medium', 'Moderate'),
  ('Maine', 'Maine Needham Festival', 74, '10 AM - 4 PM', '2026 vendor application', 'Low', 'Moderate'),
  ('Newbury, NH', 'League of NH Craftsmen Fair', 86, '10 AM - 5 PM', 'August 1-9, 2026 fair', 'Medium', 'Moderate'),
  ('New Hampshire', 'Joyce''s Craft Shows', 73, '10 AM - 4 PM', '2026 vendor application', 'Low', 'Moderate'),
  ('Woonsocket, RI', 'Autumnfest', 86, '12 PM - 8 PM', '2026 food vendor applications', 'Medium', 'Moderate'),
  ('Hartford, VT', 'Hartford VT Parks Food Truck Permit', 80, '11 AM - 7 PM', 'Designated park vending sites', 'Low', 'Moderate'),
  ('Burlington, VT', 'Burlington Farmers Market', 85, '9 AM - 2 PM', 'Every Saturday May 9 - October 31, 2026', 'Medium', 'Moderate'),
  ('Bennington, VT', 'Garlic Town USA', 84, '10 AM - 5 PM', 'September 5, 2026 festival', 'Medium', 'Moderate'),
  ('Quechee, VT', 'Quechee Balloon Festival', 87, '11 AM - 8 PM', 'Food and beverage vendor application', 'Medium', 'Moderate'),
  ('Arlington, VT', 'The OM Festival Vermont', 76, '11 AM - 7 PM', 'July 30 - August 2, 2026', 'Low', 'Moderate'),
  ('Wardsboro, VT', 'Gilfeather Turnip Festival', 72, '10 AM - 2 PM', 'October 24, 2026 marketplace', 'Low', 'Moderate'),
  ('Deerfield, NH', 'Deerfield Fair', 96, '10 AM - 9 PM', '2026 vendor/concession application', 'High', 'Moderate'),
  ('Contoocook, NH', 'Hopkinton State Fair', 95, '10 AM - 10 PM', 'Labor Day weekend fair concessions', 'High', 'Moderate'),
  ('Lancaster, NH', 'Lancaster Fair', 91, '10 AM - 10 PM', 'September 3-7, 2026 fair', 'High', 'Moderate'),
  ('Cornish, NH', 'Cornish Fair', 89, '10 AM - 8 PM', '2026 food vendor applications', 'High', 'Moderate'),
  ('Sandwich, NH', 'Sandwich Fair', 90, '9 AM - 8 PM', 'October 10-12, 2026 fair', 'High', 'Moderate'),
  ('Swanzey, NH', 'Cheshire Fair', 88, '11 AM - 9 PM', '2026 food and merchandise vendor application', 'High', 'Moderate'),
  ('Belmont, NH', 'Belknap County Fair', 84, '10 AM - 8 PM', '2026 concession application', 'Medium', 'Moderate'),
  ('North Haverhill, NH', 'North Haverhill Fair', 85, '10 AM - 9 PM', '2026 concessionaire contracts', 'Medium', 'Moderate'),
  ('Rochester, NH', 'Granite State Fair', 86, '11 AM - 9 PM', 'Vendor application', 'High', 'Moderate'),
  ('New Boston, NH', 'Hillsborough County Agricultural Fair', 82, '10 AM - 7 PM', 'September 11-13, 2026 fair', 'Medium', 'Moderate'),
  ('Deerfield, NH', 'New Hampshire Sheep & Wool Festival', 80, '9 AM - 5 PM', 'May 9-10, 2026 festival', 'Medium', 'Moderate'),
  ('Concord, NH', 'New Hampshire Book Festival', 82, '9 AM - 6 PM', 'October 3, 2026 food truck category', 'Medium', 'Low'),
  ('Hampton, NH', 'Smuttynose Food Truck Festival', 88, '11 AM - 5 PM', 'May 30, 2026 festival', 'High', 'Moderate'),
  ('Milford, NH', 'Southern NH Food Truck Festival', 89, '11 AM - 6 PM', 'August 1-2, 2026 festival', 'High', 'Moderate'),
  ('Milford, NH', 'Milford Pumpkin Festival', 87, '11 AM - 8 PM', '2026 vendor application release', 'High', 'Moderate'),
  ('Sunapee, NH', 'Sunapee Farmers Market', 78, '8 AM - 12 PM', '2026 farm/food vendor application', 'Medium', 'Moderate'),
  ('Salem, NH', 'Salem NH Farmers Market', 79, '10 AM - 2 PM', 'Summer 2026 vendor application', 'Medium', 'Moderate'),
  ('Wolfeboro, NH', 'Wolfeboro Area Farmers Market', 76, '11:30 AM - 2:30 PM', 'Thursdays May 14 - October 8, 2026', 'Medium', 'Moderate'),
  ('Candia, NH', 'Candia Farmers Market', 74, '9 AM - 12 PM', 'Third Saturdays June-October 2026', 'Low', 'Moderate'),
  ('Derry, NH', 'Derry Homegrown Farm & Artisan Market', 77, '3 PM - 7 PM', '2026 online vendor application', 'Medium', 'Moderate'),
  ('Hampton Falls, NH', 'Hampton Falls Farmers Market', 76, '10 AM - 2 PM', '2026 vendor application', 'Medium', 'Moderate'),
  ('Concord, NH', 'Concord Farmers Market', 80, '8:30 AM - 12 PM', '2026 guest vendor application', 'Medium', 'Moderate'),
  ('Chester, NH', 'Chester Town Fair', 77, '11 AM - 5 PM', '2026 food vendor application', 'Low', 'Moderate'),
  ('Newport, NH', 'Apple Pie Crafts Fair', 81, '9 AM - 3 PM', 'August 22, 2026 food vendor application', 'Medium', 'Moderate'),
  ('Sandwich, NH', 'Sandwich Farmers Market', 73, '9 AM - 12 PM', '2026 vendor application', 'Low', 'Moderate'),
  ('Rochester, NH', 'Rochester Harvest Market', 74, '3 PM - 6 PM', 'Every Tuesday in September', 'Low', 'Moderate'),
  ('Stratham & Rollinsford, NH', 'Seacoast Eat Local Winter Markets', 78, '10 AM - 2 PM', 'Winter market prepared food vendors', 'Medium', 'Low'),
  ('Milford, NH', 'New Hampshire Outdoor Expo', 79, '10 AM - 5 PM', '2026 Hampshire Dome expo', 'Medium', 'Low'),
  ('Lee, NH', 'NH Sunflower Festival', 84, '10 AM - 5 PM', 'July 25 - August 2, 2026 craft and food vendor spots', 'Medium', 'Moderate'),
  ('Warner, NH', 'Warner Fall Foliage Festival', 86, '10 AM - 6 PM', 'October 9-11, 2026 festival', 'High', 'Moderate'),
  ('Kensington, NH', 'Farm and Country Festival', 78, '10 AM - 5 PM', 'August 8-9, 2026 vendor application', 'Medium', 'Moderate'),
  ('North Conway, NH', 'White Mountains Pride Festival', 79, '11 AM - 5 PM', '2026 food vendor signup', 'Medium', 'Moderate'),
  ('Keene, NH', 'Keene Pride Fest', 80, '12 PM - 6 PM', 'September 20, 2026 food truck license', 'Medium', 'Moderate'),
  ('Nashua, NH', 'Nashua Pride Festival', 81, '3 PM - 6 PM', 'June 20, 2026 food vendor interest form', 'Medium', 'Moderate'),
  ('Peterborough, NH', 'MAXT Night Market', 78, '5 PM - 9 PM', 'August 7, 2026 vendor application', 'Medium', 'Low'),
  ('Manchester, NH', 'The Chocolate Expo New Hampshire', 83, '9 AM - 6 PM', 'October 11, 2026 food vendor application', 'High', 'Low'),
  ('Exeter, NH', 'TEAM Arts Fests', 76, '10 AM - 4 PM', '2026 Saturday food vendor applications', 'Medium', 'Moderate'),
  ('Rochester, NH', 'Lilac Family Fun Festival', 75, '11 AM - 4 PM', '2026 vendor packet', 'Low', 'Moderate'),
  ('Concord, NH', 'Market Days Festival', 88, '11 AM - 8 PM', '2026 food vendor pricing', 'High', 'Moderate'),
  ('Newington, NH', 'New Hampshire Jewish Festival', 70, '12 PM - 3 PM', 'Kosher food vendor exception', 'Low', 'Moderate');
